version: '3'

volumes:
  mysql:
    driver: local
  elasticsearch:
    driver: local

services:
    mysql:
      build:
        context: ./docker/mysql
        args:
          - MYSQL_VERSION=5.7
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - TZ=Asia/Tokyo
      volumes:
        - ./docker/data/mysql:/var/lib/mysql
      ports:
        - ${DB_PORT}:3306

    elasticsearch:
      build: ./docker/elasticsearch
      volumes:
        - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
      environment:
        - cluster.name=laravel-cluster
        - node.name=laravel-node
        - cluster.initial_master_nodes=laravel-node
      ports:
        - ${ELASTICSEARCH_HOST_HTTP_PORT}:9200
        - ${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300
